#pragma once
enum HANDBORD_TYPE
{
	HANDBORD_TYPE_HUHYOU = 0,
	HANDBORD_TYPE_KYOUSYA,
	HANDBORD_TYPE_KEIMA,
	HANDBORD_TYPE_GINN,
	HANDBORD_TYPE_KINN,
	HANDBORD_TYPE_KAKU,
	HANDBORD_TYPE_HISYA,
	HANDBORD_TYPE_NUM,

};
